CREATE ROLE debezium WITH LOGIN REPLICATION;

CREATE TABLE public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    amount_cents BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE public.noise (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payload TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE public.cdc_heartbeat (
    id INTEGER PRIMARY KEY,
    touched_at TIMESTAMPTZ NOT NULL,
    update_count BIGINT NOT NULL DEFAULT 0
);
INSERT INTO public.cdc_heartbeat (id, touched_at) VALUES (1, clock_timestamp());

GRANT CONNECT ON DATABASE cdc_lab TO debezium;
GRANT USAGE ON SCHEMA public TO debezium;
GRANT SELECT ON public.orders TO debezium;
GRANT SELECT, UPDATE ON public.cdc_heartbeat TO debezium;

CREATE PUBLICATION cdc_publication FOR TABLE public.orders, public.cdc_heartbeat;
