debezium.source.connector.class=io.debezium.connector.postgresql.PostgresConnector
debezium.source.database.hostname=postgres
debezium.source.database.port=5432
debezium.source.database.user=debezium
debezium.source.database.dbname=cdc_lab
debezium.source.topic.prefix=cdc_crashtest
debezium.source.plugin.name=pgoutput
debezium.source.slot.name=cdc_crashtest_slot
debezium.source.publication.name=cdc_publication
debezium.source.publication.autocreate.mode=disabled
debezium.source.table.include.list=public.orders,public.cdc_heartbeat
debezium.source.snapshot.mode=initial
debezium.source.offset.storage.file.filename=/debezium/data/offsets.dat
debezium.source.heartbeat.interval.ms=10000

debezium.sink.type=http
debezium.sink.http.url=http://receiver:8081/events
debezium.sink.http.timeout.ms=10000
debezium.sink.http.retries=5
debezium.sink.http.retry.interval.ms=1000

debezium.format.key=json
debezium.format.value=json
debezium.format.value.schemas.enable=false
quarkus.http.host=0.0.0.0
quarkus.http.port=8080
